-- MySQL Script generated by MySQL Workbench
-- Sat Aug 29 03:31:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema modelatgeBBDD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema modelatgeBBDD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modelatgeBBDD` DEFAULT CHARACTER SET utf8 ;
USE `modelatgeBBDD` ;

-- -----------------------------------------------------
-- Table `modelatgeBBDD`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelatgeBBDD`.`Client` (
  `nom_client` VARCHAR(20) NOT NULL COMMENT 'Anna Jofreu Garcia, Oscar Feu Gras, Jordi Mas Fom',
  `adreca_postal_client` INT NOT NULL COMMENT '08290, 08032, 08560',
  `telefon_client` INT NOT NULL COMMENT '665857485, 685996558, 695887458',
  `correu_electronic` VARCHAR(50) NOT NULL COMMENT 'mail_a@gmail.com, mail_b@gmail.com, mail_c@gmail.com',
  `data_de_registre` INT NOT NULL COMMENT '13/02/2000, 25/05/2010, 30/02/2016',
  `client_que_li_va_recomanar` VARCHAR(20) NULL COMMENT 'Joan Serrell Garcia, ,',
  PRIMARY KEY (`nom_client`),
  UNIQUE INDEX `nom_client_UNIQUE` (`nom_client` ASC) ,
  UNIQUE INDEX `correu_electronic_UNIQUE` (`correu_electronic` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelatgeBBDD`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelatgeBBDD`.`Employees` (
  `nom_empleat` VARCHAR(20) NOT NULL,
  `marca_ulleres` VARCHAR(20) NOT NULL COMMENT 'marca_a, marca_b, marca_c',
  `nom_empleat` VARCHAR(20) NOT NULL COMMENT 'Joan Ferrer Garcia, Felip Serrat Prim, Anna Sol Mas',
  PRIMARY KEY (`nom_empleat`),
  INDEX `fk_Employees_Client1_idx` (`nom_empleat` ASC) ,
  CONSTRAINT `fk_Employees_Client1`
    FOREIGN KEY (`nom_empleat`)
    REFERENCES `modelatgeBBDD`.`Client` (`nom_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelatgeBBDD`.`Suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelatgeBBDD`.`Suppliers` (
  `nif_proveidor` VARCHAR(9) NOT NULL COMMENT '58548575D, 58547854L, 58658857F',
  `nom_proveidor` VARCHAR(20) NOT NULL COMMENT 'proveidor_a, proveidor_b, proveidor_a',
  `marca_ulleres` VARCHAR(10) NOT NULL COMMENT 'marca_a, marca_b, marca_c',
  `adreca_proveidor` VARCHAR(50) NOT NULL COMMENT 'carrer girona 43 2º Barcelona Espanya, carrer Clot 3 1º Barcelona Espanya, carrer Bruc 12 3º A Barcelona Espanya',
  `telefon_proveidor` INT NOT NULL COMMENT '666524521, 665442585, 675854412',
  `fax_proveidor` INT NOT NULL COMMENT '934255214, 932253185, 932215255',
  `model_creat_proveidor` VARCHAR(20) NOT NULL COMMENT 'model_a, model_b, model_c',
  `marca_ulleres` VARCHAR(20) NOT NULL COMMENT 'marca_a, marca_b, marca_c',
  PRIMARY KEY (`nif_proveidor`),
  UNIQUE INDEX `nif_proveidor_UNIQUE` (`nif_proveidor` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelatgeBBDD`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelatgeBBDD`.`Glasses` (
  `id_ulleres` INT NOT NULL COMMENT '1,2,3',
  `marca_ulleres` VARCHAR(10) NOT NULL COMMENT 'marca_a, marca_b, marca_c',
  `graduacio_vidre_dret` INT NOT NULL COMMENT '1,2,3',
  `graduacio_vidre_esquerre` INT NOT NULL COMMENT '0,1,0',
  `tipus_de_muntura` VARCHAR(10) NOT NULL COMMENT 'flotant, pasta, flotant',
  `color_muntura` VARCHAR(10) NOT NULL COMMENT 'blanc, negre, blau',
  `color_vidre` VARCHAR(10) NOT NULL COMMENT 'verd, blau, marro',
  `preu_ulleres` INT NOT NULL COMMENT '100, 85, 45',
  `Employees_nom_empleat` VARCHAR(20) NOT NULL COMMENT 'Pau Gras, Robert Ferrer, Maria Aldaya',
  `Suppliers_nif_proveidor` VARCHAR(9) NOT NULL COMMENT '45585475G, 58524585K, 26658854L',
  PRIMARY KEY (`id_ulleres`),
  INDEX `fk_Glasses_Employees_idx` (`Employees_nom_empleat` ASC) ,
  INDEX `fk_Glasses_Suppliers1_idx` (`Suppliers_nif_proveidor` ASC) ,
  UNIQUE INDEX `id_ulleres_UNIQUE` (`id_ulleres` ASC) ,
  CONSTRAINT `fk_Glasses_Employees`
    FOREIGN KEY (`Employees_nom_empleat`)
    REFERENCES `modelatgeBBDD`.`Employees` (`nom_empleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glasses_Suppliers1`
    FOREIGN KEY (`Suppliers_nif_proveidor`)
    REFERENCES `modelatgeBBDD`.`Suppliers` (`nif_proveidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
